export const ADD_TODOS_SUCCESS = 'TODOS/ADD_TODOS_SUCCESS'
export const ADD_TODOS_FAILED = 'TODOS/ADD_TODOS_FAILED'
export const TOGGLE_TODO = 'TODOS/TOGGLE_TODO'
export const FILTER_TODOS = 'TODOS/FILTER_TODOS'

